name: Build PlatformIO Firmwares

on:
  push:
  pull_request:
  schedule:
    - cron: "0 2 * * *" # Kjør hver natt kl 02:00 UTC

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        board: [ESP8266-ESP01, WEMOS_D1_Mini, ESP32DEV]

    steps:
      # Hent repoet
      - name: Checkout repository
        uses: actions/checkout@v4

      # Cache pip + PlatformIO for raskere builds
      - name: Cache pip and PlatformIO
        uses: actions/cache@v4
        with:
          path: |
            ~/.cache/pip
            ~/.platformio/.cache
          key: ${{ runner.os }}-pio-${{ hashFiles('platformio.ini') }}

      # Installer Python
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.9.19'

      # Installer PlatformIO
      - name: Install PlatformIO Core
        run: pip install platformio==6.1.15

      # Bygg firmware for hvert miljø
      - name: Build ${{ matrix.board }}
        run: |
          echo "Bygger ${{ matrix.board }}..."
          pio run -e ${{ matrix.board }}
          BIN_PATH=$(find .pio/build/${{ matrix.board }} -maxdepth 1 -type f -name "*.bin" | head -n 1)
          echo "Fant binærfil: $BIN_PATH"
          cp "$BIN_PATH" mitsubishi2MQTT_${{ matrix.board }}.bin


      # Last opp firmware som artifact
      - name: Upload firmware artifact
        uses: actions/upload-artifact@v4
        with:
          name: mitsubishi2MQTT_${{ matrix.board }}.bin
          path: mitsubishi2MQTT_${{ matrix.board }}.bin
